- name: Print Hello World
  ansible.builtin.debug:
    msg: Hello from Role Sample

- name: Print Role from Variable
  ansible.builtin.debug:
    msg: URL - {{ URL }}

- name: Print Role from Play
  ansible.builtin.debug:
    msg: URL_PLAY - {{ URL_PLAY }}